# CMAKE generated file: DO NOT EDIT!
# Generated by "MinGW Makefiles" Generator, CMake Version 3.23

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Produce verbose output by default.
VERBOSE = 1

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = "C:\Program Files\CMake\bin\cmake.exe"

# The command to remove a file.
RM = "C:\Program Files\CMake\bin\cmake.exe" -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = C:\Users\OdinUser_2\projects\elemem\elemem\include\BayesGPc

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = C:\Users\OdinUser_2\projects\elemem\elemem\include\BayesGPc

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	"C:\Program Files\CMake\bin\cmake-gui.exe" -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	"C:\Program Files\CMake\bin\cmake.exe" --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start C:\Users\OdinUser_2\projects\elemem\elemem\include\BayesGPc\CMakeFiles C:\Users\OdinUser_2\projects\elemem\elemem\include\BayesGPc\\CMakeFiles\progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start C:\Users\OdinUser_2\projects\elemem\elemem\include\BayesGPc\CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named BayesGPc

# Build rule for target.
BayesGPc: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 BayesGPc
.PHONY : BayesGPc

# fast build rule for target.
BayesGPc/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BayesGPc.dir\build.make CMakeFiles/BayesGPc.dir/build
.PHONY : BayesGPc/fast

#=============================================================================
# Target rules for targets named BayesGPc_autogen

# Build rule for target.
BayesGPc_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 BayesGPc_autogen
.PHONY : BayesGPc_autogen

# fast build rule for target.
BayesGPc_autogen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BayesGPc_autogen.dir\build.make CMakeFiles/BayesGPc_autogen.dir/build
.PHONY : BayesGPc_autogen/fast

BayesGPc_autogen/mocs_compilation.obj: BayesGPc_autogen/mocs_compilation.cpp.obj
.PHONY : BayesGPc_autogen/mocs_compilation.obj

# target to build an object file
BayesGPc_autogen/mocs_compilation.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BayesGPc.dir\build.make CMakeFiles/BayesGPc.dir/BayesGPc_autogen/mocs_compilation.cpp.obj
.PHONY : BayesGPc_autogen/mocs_compilation.cpp.obj

BayesGPc_autogen/mocs_compilation.i: BayesGPc_autogen/mocs_compilation.cpp.i
.PHONY : BayesGPc_autogen/mocs_compilation.i

# target to preprocess a source file
BayesGPc_autogen/mocs_compilation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BayesGPc.dir\build.make CMakeFiles/BayesGPc.dir/BayesGPc_autogen/mocs_compilation.cpp.i
.PHONY : BayesGPc_autogen/mocs_compilation.cpp.i

BayesGPc_autogen/mocs_compilation.s: BayesGPc_autogen/mocs_compilation.cpp.s
.PHONY : BayesGPc_autogen/mocs_compilation.s

# target to generate assembly for a file
BayesGPc_autogen/mocs_compilation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BayesGPc.dir\build.make CMakeFiles/BayesGPc.dir/BayesGPc_autogen/mocs_compilation.cpp.s
.PHONY : BayesGPc_autogen/mocs_compilation.cpp.s

CBayesianSearch.obj: CBayesianSearch.cpp.obj
.PHONY : CBayesianSearch.obj

# target to build an object file
CBayesianSearch.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BayesGPc.dir\build.make CMakeFiles/BayesGPc.dir/CBayesianSearch.cpp.obj
.PHONY : CBayesianSearch.cpp.obj

CBayesianSearch.i: CBayesianSearch.cpp.i
.PHONY : CBayesianSearch.i

# target to preprocess a source file
CBayesianSearch.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BayesGPc.dir\build.make CMakeFiles/BayesGPc.dir/CBayesianSearch.cpp.i
.PHONY : CBayesianSearch.cpp.i

CBayesianSearch.s: CBayesianSearch.cpp.s
.PHONY : CBayesianSearch.s

# target to generate assembly for a file
CBayesianSearch.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BayesGPc.dir\build.make CMakeFiles/BayesGPc.dir/CBayesianSearch.cpp.s
.PHONY : CBayesianSearch.cpp.s

CDist.obj: CDist.cpp.obj
.PHONY : CDist.obj

# target to build an object file
CDist.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BayesGPc.dir\build.make CMakeFiles/BayesGPc.dir/CDist.cpp.obj
.PHONY : CDist.cpp.obj

CDist.i: CDist.cpp.i
.PHONY : CDist.i

# target to preprocess a source file
CDist.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BayesGPc.dir\build.make CMakeFiles/BayesGPc.dir/CDist.cpp.i
.PHONY : CDist.cpp.i

CDist.s: CDist.cpp.s
.PHONY : CDist.s

# target to generate assembly for a file
CDist.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BayesGPc.dir\build.make CMakeFiles/BayesGPc.dir/CDist.cpp.s
.PHONY : CDist.cpp.s

CGp.obj: CGp.cpp.obj
.PHONY : CGp.obj

# target to build an object file
CGp.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BayesGPc.dir\build.make CMakeFiles/BayesGPc.dir/CGp.cpp.obj
.PHONY : CGp.cpp.obj

CGp.i: CGp.cpp.i
.PHONY : CGp.i

# target to preprocess a source file
CGp.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BayesGPc.dir\build.make CMakeFiles/BayesGPc.dir/CGp.cpp.i
.PHONY : CGp.cpp.i

CGp.s: CGp.cpp.s
.PHONY : CGp.s

# target to generate assembly for a file
CGp.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BayesGPc.dir\build.make CMakeFiles/BayesGPc.dir/CGp.cpp.s
.PHONY : CGp.cpp.s

CKern.obj: CKern.cpp.obj
.PHONY : CKern.obj

# target to build an object file
CKern.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BayesGPc.dir\build.make CMakeFiles/BayesGPc.dir/CKern.cpp.obj
.PHONY : CKern.cpp.obj

CKern.i: CKern.cpp.i
.PHONY : CKern.i

# target to preprocess a source file
CKern.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BayesGPc.dir\build.make CMakeFiles/BayesGPc.dir/CKern.cpp.i
.PHONY : CKern.cpp.i

CKern.s: CKern.cpp.s
.PHONY : CKern.s

# target to generate assembly for a file
CKern.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BayesGPc.dir\build.make CMakeFiles/BayesGPc.dir/CKern.cpp.s
.PHONY : CKern.cpp.s

CMatrix.obj: CMatrix.cpp.obj
.PHONY : CMatrix.obj

# target to build an object file
CMatrix.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BayesGPc.dir\build.make CMakeFiles/BayesGPc.dir/CMatrix.cpp.obj
.PHONY : CMatrix.cpp.obj

CMatrix.i: CMatrix.cpp.i
.PHONY : CMatrix.i

# target to preprocess a source file
CMatrix.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BayesGPc.dir\build.make CMakeFiles/BayesGPc.dir/CMatrix.cpp.i
.PHONY : CMatrix.cpp.i

CMatrix.s: CMatrix.cpp.s
.PHONY : CMatrix.s

# target to generate assembly for a file
CMatrix.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BayesGPc.dir\build.make CMakeFiles/BayesGPc.dir/CMatrix.cpp.s
.PHONY : CMatrix.cpp.s

CMltools.obj: CMltools.cpp.obj
.PHONY : CMltools.obj

# target to build an object file
CMltools.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BayesGPc.dir\build.make CMakeFiles/BayesGPc.dir/CMltools.cpp.obj
.PHONY : CMltools.cpp.obj

CMltools.i: CMltools.cpp.i
.PHONY : CMltools.i

# target to preprocess a source file
CMltools.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BayesGPc.dir\build.make CMakeFiles/BayesGPc.dir/CMltools.cpp.i
.PHONY : CMltools.cpp.i

CMltools.s: CMltools.cpp.s
.PHONY : CMltools.s

# target to generate assembly for a file
CMltools.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BayesGPc.dir\build.make CMakeFiles/BayesGPc.dir/CMltools.cpp.s
.PHONY : CMltools.cpp.s

CNoise.obj: CNoise.cpp.obj
.PHONY : CNoise.obj

# target to build an object file
CNoise.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BayesGPc.dir\build.make CMakeFiles/BayesGPc.dir/CNoise.cpp.obj
.PHONY : CNoise.cpp.obj

CNoise.i: CNoise.cpp.i
.PHONY : CNoise.i

# target to preprocess a source file
CNoise.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BayesGPc.dir\build.make CMakeFiles/BayesGPc.dir/CNoise.cpp.i
.PHONY : CNoise.cpp.i

CNoise.s: CNoise.cpp.s
.PHONY : CNoise.s

# target to generate assembly for a file
CNoise.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BayesGPc.dir\build.make CMakeFiles/BayesGPc.dir/CNoise.cpp.s
.PHONY : CNoise.cpp.s

COptimisable.obj: COptimisable.cpp.obj
.PHONY : COptimisable.obj

# target to build an object file
COptimisable.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BayesGPc.dir\build.make CMakeFiles/BayesGPc.dir/COptimisable.cpp.obj
.PHONY : COptimisable.cpp.obj

COptimisable.i: COptimisable.cpp.i
.PHONY : COptimisable.i

# target to preprocess a source file
COptimisable.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BayesGPc.dir\build.make CMakeFiles/BayesGPc.dir/COptimisable.cpp.i
.PHONY : COptimisable.cpp.i

COptimisable.s: COptimisable.cpp.s
.PHONY : COptimisable.s

# target to generate assembly for a file
COptimisable.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BayesGPc.dir\build.make CMakeFiles/BayesGPc.dir/COptimisable.cpp.s
.PHONY : COptimisable.cpp.s

CSearchComparison.obj: CSearchComparison.cpp.obj
.PHONY : CSearchComparison.obj

# target to build an object file
CSearchComparison.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BayesGPc.dir\build.make CMakeFiles/BayesGPc.dir/CSearchComparison.cpp.obj
.PHONY : CSearchComparison.cpp.obj

CSearchComparison.i: CSearchComparison.cpp.i
.PHONY : CSearchComparison.i

# target to preprocess a source file
CSearchComparison.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BayesGPc.dir\build.make CMakeFiles/BayesGPc.dir/CSearchComparison.cpp.i
.PHONY : CSearchComparison.cpp.i

CSearchComparison.s: CSearchComparison.cpp.s
.PHONY : CSearchComparison.s

# target to generate assembly for a file
CSearchComparison.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BayesGPc.dir\build.make CMakeFiles/BayesGPc.dir/CSearchComparison.cpp.s
.PHONY : CSearchComparison.cpp.s

CTransform.obj: CTransform.cpp.obj
.PHONY : CTransform.obj

# target to build an object file
CTransform.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BayesGPc.dir\build.make CMakeFiles/BayesGPc.dir/CTransform.cpp.obj
.PHONY : CTransform.cpp.obj

CTransform.i: CTransform.cpp.i
.PHONY : CTransform.i

# target to preprocess a source file
CTransform.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BayesGPc.dir\build.make CMakeFiles/BayesGPc.dir/CTransform.cpp.i
.PHONY : CTransform.cpp.i

CTransform.s: CTransform.cpp.s
.PHONY : CTransform.s

# target to generate assembly for a file
CTransform.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BayesGPc.dir\build.make CMakeFiles/BayesGPc.dir/CTransform.cpp.s
.PHONY : CTransform.cpp.s

GridSearch.obj: GridSearch.cpp.obj
.PHONY : GridSearch.obj

# target to build an object file
GridSearch.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BayesGPc.dir\build.make CMakeFiles/BayesGPc.dir/GridSearch.cpp.obj
.PHONY : GridSearch.cpp.obj

GridSearch.i: GridSearch.cpp.i
.PHONY : GridSearch.i

# target to preprocess a source file
GridSearch.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BayesGPc.dir\build.make CMakeFiles/BayesGPc.dir/GridSearch.cpp.i
.PHONY : GridSearch.cpp.i

GridSearch.s: GridSearch.cpp.s
.PHONY : GridSearch.s

# target to generate assembly for a file
GridSearch.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BayesGPc.dir\build.make CMakeFiles/BayesGPc.dir/GridSearch.cpp.s
.PHONY : GridSearch.cpp.s

ndlassert.obj: ndlassert.cpp.obj
.PHONY : ndlassert.obj

# target to build an object file
ndlassert.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BayesGPc.dir\build.make CMakeFiles/BayesGPc.dir/ndlassert.cpp.obj
.PHONY : ndlassert.cpp.obj

ndlassert.i: ndlassert.cpp.i
.PHONY : ndlassert.i

# target to preprocess a source file
ndlassert.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BayesGPc.dir\build.make CMakeFiles/BayesGPc.dir/ndlassert.cpp.i
.PHONY : ndlassert.cpp.i

ndlassert.s: ndlassert.cpp.s
.PHONY : ndlassert.s

# target to generate assembly for a file
ndlassert.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BayesGPc.dir\build.make CMakeFiles/BayesGPc.dir/ndlassert.cpp.s
.PHONY : ndlassert.cpp.s

ndlfortran.obj: ndlfortran.f.obj
.PHONY : ndlfortran.obj

# target to build an object file
ndlfortran.f.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BayesGPc.dir\build.make CMakeFiles/BayesGPc.dir/ndlfortran.f.obj
.PHONY : ndlfortran.f.obj

ndlfortran.i: ndlfortran.f.i
.PHONY : ndlfortran.i

# target to preprocess a source file
ndlfortran.f.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BayesGPc.dir\build.make CMakeFiles/BayesGPc.dir/ndlfortran.f.i
.PHONY : ndlfortran.f.i

ndlfortran.s: ndlfortran.f.s
.PHONY : ndlfortran.s

# target to generate assembly for a file
ndlfortran.f.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BayesGPc.dir\build.make CMakeFiles/BayesGPc.dir/ndlfortran.f.s
.PHONY : ndlfortran.f.s

ndlfortran_lbfgsb.obj: ndlfortran_lbfgsb.f.obj
.PHONY : ndlfortran_lbfgsb.obj

# target to build an object file
ndlfortran_lbfgsb.f.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BayesGPc.dir\build.make CMakeFiles/BayesGPc.dir/ndlfortran_lbfgsb.f.obj
.PHONY : ndlfortran_lbfgsb.f.obj

ndlfortran_lbfgsb.i: ndlfortran_lbfgsb.f.i
.PHONY : ndlfortran_lbfgsb.i

# target to preprocess a source file
ndlfortran_lbfgsb.f.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BayesGPc.dir\build.make CMakeFiles/BayesGPc.dir/ndlfortran_lbfgsb.f.i
.PHONY : ndlfortran_lbfgsb.f.i

ndlfortran_lbfgsb.s: ndlfortran_lbfgsb.f.s
.PHONY : ndlfortran_lbfgsb.s

# target to generate assembly for a file
ndlfortran_lbfgsb.f.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BayesGPc.dir\build.make CMakeFiles/BayesGPc.dir/ndlfortran_lbfgsb.f.s
.PHONY : ndlfortran_lbfgsb.f.s

ndlfortran_linpack.obj: ndlfortran_linpack.f.obj
.PHONY : ndlfortran_linpack.obj

# target to build an object file
ndlfortran_linpack.f.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BayesGPc.dir\build.make CMakeFiles/BayesGPc.dir/ndlfortran_linpack.f.obj
.PHONY : ndlfortran_linpack.f.obj

ndlfortran_linpack.i: ndlfortran_linpack.f.i
.PHONY : ndlfortran_linpack.i

# target to preprocess a source file
ndlfortran_linpack.f.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BayesGPc.dir\build.make CMakeFiles/BayesGPc.dir/ndlfortran_linpack.f.i
.PHONY : ndlfortran_linpack.f.i

ndlfortran_linpack.s: ndlfortran_linpack.f.s
.PHONY : ndlfortran_linpack.s

# target to generate assembly for a file
ndlfortran_linpack.f.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BayesGPc.dir\build.make CMakeFiles/BayesGPc.dir/ndlfortran_linpack.f.s
.PHONY : ndlfortran_linpack.f.s

ndlfortran_timer.obj: ndlfortran_timer.f.obj
.PHONY : ndlfortran_timer.obj

# target to build an object file
ndlfortran_timer.f.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BayesGPc.dir\build.make CMakeFiles/BayesGPc.dir/ndlfortran_timer.f.obj
.PHONY : ndlfortran_timer.f.obj

ndlfortran_timer.i: ndlfortran_timer.f.i
.PHONY : ndlfortran_timer.i

# target to preprocess a source file
ndlfortran_timer.f.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BayesGPc.dir\build.make CMakeFiles/BayesGPc.dir/ndlfortran_timer.f.i
.PHONY : ndlfortran_timer.f.i

ndlfortran_timer.s: ndlfortran_timer.f.s
.PHONY : ndlfortran_timer.s

# target to generate assembly for a file
ndlfortran_timer.f.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BayesGPc.dir\build.make CMakeFiles/BayesGPc.dir/ndlfortran_timer.f.s
.PHONY : ndlfortran_timer.f.s

ndlstrutil.obj: ndlstrutil.cpp.obj
.PHONY : ndlstrutil.obj

# target to build an object file
ndlstrutil.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BayesGPc.dir\build.make CMakeFiles/BayesGPc.dir/ndlstrutil.cpp.obj
.PHONY : ndlstrutil.cpp.obj

ndlstrutil.i: ndlstrutil.cpp.i
.PHONY : ndlstrutil.i

# target to preprocess a source file
ndlstrutil.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BayesGPc.dir\build.make CMakeFiles/BayesGPc.dir/ndlstrutil.cpp.i
.PHONY : ndlstrutil.cpp.i

ndlstrutil.s: ndlstrutil.cpp.s
.PHONY : ndlstrutil.s

# target to generate assembly for a file
ndlstrutil.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BayesGPc.dir\build.make CMakeFiles/BayesGPc.dir/ndlstrutil.cpp.s
.PHONY : ndlstrutil.cpp.s

ndlutil.obj: ndlutil.cpp.obj
.PHONY : ndlutil.obj

# target to build an object file
ndlutil.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BayesGPc.dir\build.make CMakeFiles/BayesGPc.dir/ndlutil.cpp.obj
.PHONY : ndlutil.cpp.obj

ndlutil.i: ndlutil.cpp.i
.PHONY : ndlutil.i

# target to preprocess a source file
ndlutil.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BayesGPc.dir\build.make CMakeFiles/BayesGPc.dir/ndlutil.cpp.i
.PHONY : ndlutil.cpp.i

ndlutil.s: ndlutil.cpp.s
.PHONY : ndlutil.s

# target to generate assembly for a file
ndlutil.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BayesGPc.dir\build.make CMakeFiles/BayesGPc.dir/ndlutil.cpp.s
.PHONY : ndlutil.cpp.s

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... edit_cache
	@echo ... rebuild_cache
	@echo ... BayesGPc_autogen
	@echo ... BayesGPc
	@echo ... BayesGPc_autogen/mocs_compilation.obj
	@echo ... BayesGPc_autogen/mocs_compilation.i
	@echo ... BayesGPc_autogen/mocs_compilation.s
	@echo ... CBayesianSearch.obj
	@echo ... CBayesianSearch.i
	@echo ... CBayesianSearch.s
	@echo ... CDist.obj
	@echo ... CDist.i
	@echo ... CDist.s
	@echo ... CGp.obj
	@echo ... CGp.i
	@echo ... CGp.s
	@echo ... CKern.obj
	@echo ... CKern.i
	@echo ... CKern.s
	@echo ... CMatrix.obj
	@echo ... CMatrix.i
	@echo ... CMatrix.s
	@echo ... CMltools.obj
	@echo ... CMltools.i
	@echo ... CMltools.s
	@echo ... CNoise.obj
	@echo ... CNoise.i
	@echo ... CNoise.s
	@echo ... COptimisable.obj
	@echo ... COptimisable.i
	@echo ... COptimisable.s
	@echo ... CSearchComparison.obj
	@echo ... CSearchComparison.i
	@echo ... CSearchComparison.s
	@echo ... CTransform.obj
	@echo ... CTransform.i
	@echo ... CTransform.s
	@echo ... GridSearch.obj
	@echo ... GridSearch.i
	@echo ... GridSearch.s
	@echo ... ndlassert.obj
	@echo ... ndlassert.i
	@echo ... ndlassert.s
	@echo ... ndlfortran.obj
	@echo ... ndlfortran.i
	@echo ... ndlfortran.s
	@echo ... ndlfortran_lbfgsb.obj
	@echo ... ndlfortran_lbfgsb.i
	@echo ... ndlfortran_lbfgsb.s
	@echo ... ndlfortran_linpack.obj
	@echo ... ndlfortran_linpack.i
	@echo ... ndlfortran_linpack.s
	@echo ... ndlfortran_timer.obj
	@echo ... ndlfortran_timer.i
	@echo ... ndlfortran_timer.s
	@echo ... ndlstrutil.obj
	@echo ... ndlstrutil.i
	@echo ... ndlstrutil.s
	@echo ... ndlutil.obj
	@echo ... ndlutil.i
	@echo ... ndlutil.s
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

